project:
  type: website
  output-dir: docs

website:
  title: "tidymodels"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: 참고자료
        menu:
          - text: "Tidy Modeling with R"
            href: https://www.tmwr.org/
          - text: "Supervised Machine Learning for Text Analysis in R"
            href: https://smltar.com/
          - text: "ISLR tidymodels labs"
            href: https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/
          - text: "Statistical Inference via Data Science: A ModernDive into R and the Tidyverse"
            href: https://moderndive.com/index.html
          - text: "Feature Engineering and Selection: A Practical Approach for Predictive Models"
            href: https://bookdown.org/max/FES/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

execute:
  freeze: true
  echo: true
  warning: false
